/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: '#9f403d',
        'error-dim': '#4e0309',
        'error-container': '#fe8983',
        'on-error': '#fff7f6',
        'on-error-container': '#752121',

        primary: '#2d6197',
        'primary-dim': '#1d548a',
        'primary-container': '#d2e4ff',
        'primary-fixed': '#d2e4ff',
        'primary-fixed-dim': '#bad7ff',
        'on-primary': '#f5f7ff',
        'on-primary-container': '#1c5489',
        'on-primary-fixed': '#004173',
        'on-primary-fixed-variant': '#295e94',
        'inverse-primary': '#92c1fe',

        secondary: '#526074',
        'secondary-dim': '#465468',
        'secondary-container': '#d5e3fc',
        'secondary-fixed': '#d5e3fc',
        'secondary-fixed-dim': '#c7d5ed',
        'on-secondary': '#f8f8ff',
        'on-secondary-container': '#455367',
        'on-secondary-fixed': '#324053',
        'on-secondary-fixed-variant': '#4e5c71',

        tertiary: '#ba1e21',
        'tertiary-dim': '#a80c16',
        'tertiary-container': '#fd5049',
        'tertiary-fixed': '#fd5049',
        'tertiary-fixed-dim': '#eb433e',
        'on-tertiary': '#fff7f6',
        'on-tertiary-container': '#1f0001',
        'on-tertiary-fixed': '#000000',
        'on-tertiary-fixed-variant': '#3b0002',

        background: '#f6fafe',
        'on-background': '#26343d',

        surface: '#f6fafe',
        'surface-dim': '#cadde9',
        'surface-bright': '#f6fafe',
        'surface-tint': '#2d6197',
        'surface-variant': '#d5e5ef',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4fa',
        'surface-container': '#e5eff7',
        'surface-container-high': '#ddeaf3',
        'surface-container-highest': '#d5e5ef',
        'on-surface': '#26343d',
        'on-surface-variant': '#52616a',

        outline: '#6e7d86',
        'outline-variant': '#a4b4be',

        'inverse-surface': '#0a0f12',
        'inverse-on-surface': '#999da1',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-sm': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.02em' }],
        'headline-sm': ['1.5rem', { lineHeight: '2rem' }],
        'title-lg': ['1.375rem', { lineHeight: '1.75rem' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem' }],
        'label-sm': ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.05em' }],
      },
    },
  },
  plugins: [],
}
